name: Terragrunt Workflow

on:
  workflow_dispatch:
    inputs:
      terragrunt:
        description: 'Terragrunt action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - 'plan'
          - 'apply'

jobs:
  terragrunt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64 -o terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Run Terragrunt command
        run: |
          echo "Running terragrunt ${{ github.event.inputs.terragrunt }}"
          cd infra/test
          terragrunt ${{ github.event.inputs.terragrunt }}
